version: "2"

services:
    Mysql:
        image: datamysql:v1
        tty: true
        ports:
          - "3306:3306"
        environment:
          - MYSQL_ROOT_PASSWORD=root
    jdk8:
        image: myjdk:v1
        tty: true
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_IP=192.168.99.100
            - MYSQL_PORT=3306
            - MYSQL_DATABASES=sakila
            - MYSQL_USER=root
            - CountryID=2
            - CustomerID=5
        
        depends_on:
            - Mysql