From registry.saas.hand-china.com/hap-cloud/base:latest 

ADD Exam1.jar Exam1.jar

ADD Exam2.jar Exam2.jar

CMD java -jar  Exam1.jar  $MYSQL_IP  $MYSQL_PORT  $MYSQL_DATABASES  $MYSQL_USER  $MYSQL_ROOT_PASSWORD  $CountryID  $CustomerID 

CMD java -jar  Exam2.jar  $MYSQL_IP  $MYSQL_PORT  $MYSQL_DATABASES  $MYSQL_USER  $MYSQL_ROOT_PASSWORD  $CountryID  $CustomerID 
