FROM registry.saas.hand-china.com/tools/mysql:5.6

COPY JavaTest3/sakila-db/sakila-data.sql

COPY JavaTest3/sakila-db/sakila-schema.sql

RUN java -jar Exam1/target/Exam1.jar
    java -jar Exam2/target/Exam2.jar
